dist: xenial
sudo: false
language: scala

scala_version_211: &scala_version_211 2.11.12
scala_version_212: &scala_version_212 2.12.8
scala_version_213: &scala_version_213 2.13.0-M5
scala_version_docs: &scala_version_docs 2.12.8
  
java11: &java_11 openjdk11
java12: &java_12 openjdk12

stages:
  - name: tests
  - name: publish
    if: (branch = master AND type = push AND tag IS blank)
  - name: release
    if: tag IS present

jobs:
  include:
    - &tests
      stage: tests
      env: TEST="tests"
      script:
        - sbt ++$TRAVIS_SCALA_VERSION test doc mimaReportBinaryIssues scalafmtCheckAll
      scala: *scala_version_211
      jdk: *java_11
    - <<: *tests
      scala: *scala_version_212
    - <<: *tests
      scala: *scala_version_213
    - <<: *tests
      scala: *scala_version_212
      jdk: *java_12

    - stage: tests
      env: TEST="site"
      scala: *scala_version_docs
      script:
        - sbt ++$TRAVIS_SCALA_VERSION docs/makeSite

    - &publish
      stage: publish
      env: TEST="publish"
      jdk: *java_11
      scala: *scala_version_docs
      before_script:
        - echo $PGP_SECRET | base64 --decode | gpg --import
        - eval "$(ssh-agent -s)"
        - echo $SSH_PRIVATE_KEY | base64 --decode | ssh-add -
      script:
        - sbt ++$TRAVIS_SCALA_VERSION +publishSigned
      after_success:
        - sbt ++$TRAVIS_SCALA_VERSION docs/makeSite docs/ghpagesPushSite

    - <<: *tests
      stage: release
      env: TEST="release"
      script:
        - sbt ++$TRAVIS_SCALA_VERSION sonatypeOpen +publishSigned sonatypeRelease

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
